# Generated by Django 4.2.3 on 2023-09-04 23:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('firstapp', '0003_another'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Another',
        ),
    ]
